config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


from rooms import views as room_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]


# URL경로와 우리의 DIR경로가 꼭 같을 필요는 없음. 이렇게 MEDIA라고하는 folder루트에 MEDIA_ROOT를 추가해주어도됨.

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # 반드시 붙여주어야함.

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"  # config/urls.py의 namespace와 같아야함.


urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete-verification"),
]

templates/partials/footer.html
<footer class="container mx-auto text-center py-10 border-t font-medium text-gray-500 flex flex-col">
    <span>
        Please do not copy me
    </span>
    <span>
        &copy; 2019 Nbnb. Inc all right reserved. 
    </span>
</footer>

templates/partials/nav.html
<nav>
    <ul class="flex items-center text-sm font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link"><a href="{% url "users:logout" %}">Log out</a> </li>
    {% else %}
        <li class="nav_link"><a href="{% url "users:login" %}">Log in</a></li>
        <li class="nav_link"><a href="{% url "users:signup" %}">Sign up</a></li>
    {% endif %}
    </ul>
</nav>

templates/partials/room_card.html
<div class="w-1/4 mb-10 px-2">
    <a href=" {% url 'rooms:detail' room.pk %}">
        <div class="w-full h-64 bg-cover bg-center rounded-lg mb-2" style="background-image:url({{room.first_photo}})">
        </div>

        <div class="flex justify-between mb-2">
            <div class="w-4/5 overflow-hidden flex">
                {% if room.host.superhost %}
                    <span class="uppercase font-medium text-xs border-black border rounded-md p-px mr-2">superhost</span>                 
                {% endif %}
                <span class="text-sm text-gray-600 truncate">{{room.city}}, {{room.country.name}}</span>
            </div>

    <!-- font awsome -->
            <span class="text-sm items-center">
                <i class="fas fa-star text-red-500 mr-1"></i>{{room.total_rating}}
            </span >

        </div>
        <span class="text-black w-11/12 truncate overflow-hidden">{{room.name}}</span>
    </a>
</div>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url "users:github-login" %}" class="btn border-2 text-gray-700 mb-2 border-gray-700 font-semibold">
        <i class="fab fa-github-alt pr-3 fa-lg"></i>Continue with Github
    </a>
    <a href="{% url "users:kakao-login" %}" class="btn my-3 border border-yellow-600 text-yellow-700 py-5 bg-yellow-400 font-semibold">
        <i class="fas fa-comment pr-3 fa-lg"></i>Continue with KAKAO
    </a>
</div>

<div class="flex items-center w-full my-5">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-bold font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>