config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static


from rooms import views as room_views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("", include("core.urls", namespace="core")),
]


# URL경로와 우리의 DIR경로가 꼭 같을 필요는 없음. 이렇게 MEDIA라고하는 folder루트에 MEDIA_ROOT를 추가해주어도됨.

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # 반드시 붙여주어야함.

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"  # config/urls.py의 namespace와 같아야함.


urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <title>{% block  page_title %}{% endblock page_title %} &Nbnb </title>
</head> 

<body class="text-gray-800 mt-24 font-light">
    <header class="container max-w-full inset-0 flex items-center justify-between pr-6 h-20 border-b border-gray-400 fixed bg-white">
        <div class="flex items-center w-2/5">
            <a href="{% url "core:home" %}" class="mx-6 my-1 h-8 w-8" >
                <img class="w-full h-full" src="{% static 'img/logo.png' %}">
            </a>    
            {% block search-bar %}
            <form class="w-4/5" method="get" action="{% url "rooms:search" %}" >
                <input class="w-full search-box border px-5 py-2 text-nm fomt-medium placeholder-gray-600 text-gray-900 rounded-sm shadow-md hover:shadow-lg focus:outline-none" name="city" value="{{city}}" placeholder="Search by City"/>
            </form>
            {% endblock search-bar %}
        </div>
        {% include "partials/nav.html" %}
    </header>

    {% block content %}{% endblock content %}
    {% include "partials/footer.html" %}
</body>

</html>